--- Auto-rename remotes based on calling script name
newButton(
    "Auto-Rename Remotes",
    function() 
        return "Click to rename remotes based on their calling script name" 
    end,
    function()
        local renameCommands = {}
        local remoteStats = {}
        
        -- Собираем статистику по ремоутам из логов
        for _, log in ipairs(logs) do
            if log and log.Remote and log.Remote:IsA("RemoteEvent") or log.Remote:IsA("RemoteFunction") then
                local remote = log.Remote
                local remoteId = tostring(remote)
                
                if not remoteStats[remoteId] then
                    -- Получаем имя из скрипта-источника
                    local sourceName = "Unknown"
                    if log.Source then
                        -- Пробуем получить имя скрипта
                        local script = log.Source
                        if script:IsA("LocalScript") or script:IsA("Script") then
                            -- Получаем путь скрипта
                            local path = ""
                            local current = script
                            while current and current ~= game do
                                if path == "" then
                                    path = current.Name
                                else
                                    path = current.Name .. "_" .. path
                                end
                                current = current.Parent
                            end
                            sourceName = path:gsub("[^%w_]", "_"):sub(1, 30)
                        end
                    elseif log.Function then
                        -- Пробуем получить имя из функции
                        local funcInfo = info(log.Function, "n")
                        if funcInfo and funcInfo ~= "" then
                            sourceName = funcInfo:gsub("[^%w_]", "_")
                        end
                    end
                    
                    -- Формируем новое имя
                    local newName = string.format("%s_Remote%d", 
                        sourceName, 
                        math.random(100, 999))
                    
                    -- Проверяем, не слишком ли длинное имя
                    if #newName > 50 then
                        newName = newName:sub(1, 50)
                    end
                    
                    remoteStats[remoteId] = {
                        remote = remote,
                        originalName = remote.Name,
                        newName = newName,
                        source = sourceName,
                        className = remote.ClassName,
                        parent = remote.Parent
                    }
                end
            end
        end
        
        -- Создаем команды для переименования
        for _, stat in pairs(remoteStats) do
            local command = string.format([[
-- Renaming: %s -> %s
-- Source: %s | Class: %s
local remote = game:GetService("%s"):FindFirstChild("%s")
if remote then
    remote.Name = "%s"
    print("✓ Renamed: " .. tostring(remote) .. " -> %s")
end
]], 
                stat.originalName,
                stat.newName,
                stat.source,
                stat.className,
                stat.parent.ClassName,
                stat.originalName,
                stat.newName,
                stat.newName
            )
            
            table.insert(renameCommands, command)
        end
        
        -- Формируем полный скрипт
        local fullScript = "-- AUTO RENAME REMOTES SCRIPT\n"
        fullScript = fullScript .. "-- Generated by SimpleSpy\n"
        fullScript = fullScript .. "-- Renames remotes based on calling script\n\n"
        
        if #renameCommands > 0 then
            fullScript = fullScript .. table.concat(renameCommands, "\n\n")
            
            -- Добавляем итоговую информацию
            fullScript = fullScript .. string.format("\n\n-- Total remotes to rename: %d", #renameCommands)
            fullScript = fullScript .. string.format("\nprint(\"Script completed! Renamed %d remotes\")", #renameCommands)
            
            -- Копируем в буфер обмена
            setclipboard(fullScript)
            
            -- Показываем результат
            TextLabel.Text = string.format("Generated %d rename commands!\nScript copied to clipboard.", #renameCommands)
            
            -- Создаем меню с деталями
            local details = "=== REMOTE RENAME DETAILS ===\n\n"
            for id, stat in pairs(remoteStats) do
                details = details .. string.format("• %s -> %s\n", 
                    stat.originalName, 
                    stat.newName)
                details = details .. string.format("  Source: %s | Parent: %s\n\n", 
                    stat.source, 
                    stat.parent:GetFullName())
            end
            
            -- Выводим детали в новом окне
            local DetailsFrame = Create("Frame", {
                Parent = SimpleSpy3,
                Name = "RenameDetails",
                BackgroundColor3 = Color3.fromRGB(37, 36, 38),
                BorderSizePixel = 0,
                Position = UDim2.new(0.5, -150, 0.5, -100),
                Size = UDim2.new(0, 300, 0, 200),
                ZIndex = 10
            })
            
            local DetailsScroll = Create("ScrollingFrame", {
                Parent = DetailsFrame,
                BackgroundColor3 = Color3.fromRGB(53, 52, 55),
                BorderSizePixel = 0,
                Position = UDim2.new(0, 5, 0, 30),
                Size = UDim2.new(1, -10, 1, -40),
                CanvasSize = UDim2.new(0, 0, 0, 0),
                ScrollBarThickness = 4
            })
            
            local DetailsText = Create("TextLabel", {
                Parent = DetailsScroll,
                BackgroundTransparency = 1,
                Size = UDim2.new(1, 0, 0, #remoteStats * 60),
                Text = details,
                TextColor3 = Color3.new(1, 1, 1),
                TextSize = 12,
                TextXAlignment = Enum.TextXAlignment.Left,
                TextYAlignment = Enum.TextYAlignment.Top,
                TextWrapped = true
            })
            
            DetailsScroll.CanvasSize = UDim2.new(0, 0, 0, DetailsText.AbsoluteSize.Y)
            
            local Title = Create("TextLabel", {
                Parent = DetailsFrame,
                BackgroundColor3 = Color3.fromRGB(37, 35, 38),
                BorderSizePixel = 0,
                Size = UDim2.new(1, 0, 0, 30),
                Text = "Rename Details",
                TextColor3 = Color3.new(1, 1, 1),
                TextSize = 14
            })
            
            local CloseButton = Create("TextButton", {
                Parent = DetailsFrame,
                BackgroundColor3 = Color3.fromRGB(255, 60, 60),
                BorderSizePixel = 0,
                Position = UDim2.new(1, -25, 0, 5),
                Size = UDim2.new(0, 20, 0, 20),
                Text = "X",
                TextColor3 = Color3.new(1, 1, 1),
                TextSize = 12,
                ZIndex = 11
            })
            
            CloseButton.MouseButton1Click:Connect(function()
                DetailsFrame:Destroy()
            end)
            
            -- Автоматически выполняем переименование
            spawn(function()
                local successCount = 0
                for _, stat in pairs(remoteStats) do
                    local success = pcall(function()
                        stat.remote.Name = stat.newName
                    end)
                    
                    if success then
                        successCount = successCount + 1
                        print(string.format("✓ Renamed in-game: %s -> %s", 
                            stat.originalName, 
                            stat.newName))
                    else
                        print(string.format("✗ Failed to rename: %s", 
                            stat.originalName))
                    end
                    
                    wait(0.1) -- Небольшая задержка между операциями
                end
                
                TextLabel.Text = string.format("Successfully renamed %d/%d remotes in-game!", 
                    successCount, 
                    #renameCommands)
            end)
        else
            TextLabel.Text = "No remotes found in logs to rename!"
        end
    end
)
